# this is mostly generated by ChatGPT (GPT 3.5-turbo)
import discord
from discord.ext import commands

intents = discord.Intents.default()
intents.message_content = True
intents.reactions = True
intents.presences = True

description = '''This is the alternative version to "The Phantom", based on discord.py and discord.ext'''

bot = commands.Bot(intents = intents, description = description, command_prefix='$')

@bot.event
async def on_ready():
    print('I logged in!')

@bot.command(name='embed')
async def embed(ctx, title, description, color, field_name, field_content, footer):
    embed = discord.Embed(title=str(title), description=str(description), color=discord.Color(int(color, 16)))
    embed.add_field(name=str(field_name), value=str(field_content), inline=False)
    embed.set_footer(text=str(footer))
    await ctx.send(embed=embed)

@bot.command(name='say')
async def say(ctx, arg):
    await ctx.send(arg)


@bot.command()
async def joined(ctx, member: discord.Member):
    """Says when a member joined."""
    await ctx.send(f'{member.name} joined {discord.utils.format_dt(member.joined_at)}')


@bot.event
async def on_raw_reaction_add(payload: discord.RawReactionActionEvent):
    if payload.channel_id == 1095766880771383406 and payload.message_id == 1095767381957156944:
        if str(payload.emoji) == '1️⃣':
            guild = bot.get_guild(payload.guild_id)
            member = await guild.fetch_member(payload.user_id)
            role = discord.utils.get(guild.roles, name='ONE')
            await member.add_roles(role)
            await member.send(f'I just assigned the role "{role.name}" to you!')
        elif str(payload.emoji) == '2️⃣':
            guild = bot.get_guild(payload.guild_id)
            member = await guild.fetch_member(payload.user_id)
            role = discord.utils.get(guild.roles, name='TWO')
            await member.add_roles(role)
            await member.send(f'I just assigned the role "{role.name}" to you!')

@bot.event
async def on_raw_reaction_remove(payload: discord.RawReactionActionEvent):
    if payload.channel_id == 1095766880771383406 and payload.message_id == 1095767381957156944:
        if str(payload.emoji) == '1️⃣':
            guild = bot.get_guild(payload.guild_id)
            member = await guild.fetch_member(payload.user_id)
            role = discord.utils.get(guild.roles, name='ONE')
            await member.remove_roles(role)
            await member.send(f'I just removed your "{role.name}" role!')
        elif str(payload.emoji) == '2️⃣':
            guild = bot.get_guild(payload.guild_id)
            member = await guild.fetch_member(payload.user_id)
            role = discord.utils.get(guild.roles, name='TWO')
            await member.remove_roles(role)
            await member.send(f'I just removed your "{role.name}" role!')


#bot.add_command(test)  # registering a .ext command

with open('token', 'r') as tkn:
    token = str(tkn.read())

bot.run(token)